group 'com.razorpay.razorpay_turbo_standard'
version '1.1.4'

buildscript {
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.razorpay.razorpay_turbo_standard'
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lintOptions {
        disable 'InvalidPackage'
    }
    
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        // api 'com.razorpay:checkout:1.6.+'
        implementation 'com.google.code.gson:gson:2.8.8'
        compileOnly "com.razorpay:checkout:1.6.41"
        compileOnly "com.razorpay:razorpay-turbo:2.1.0"
        compileOnly "com.razorpay:turbo-ui:2.1.0"
    }
}
